plugins {
    id 'com.android.application'
}

android {
    namespace 'com.together.camera'
    compileSdk 35

    defaultConfig {
        applicationId 'com.together.camera.hq'
        minSdk 24
        targetSdk 35
        versionCode 11
        versionName '1.1.1'
    }

    signingConfigs {
        debug {
            enableV1Signing true
            enableV2Signing true
        }
    }

    buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
        release {
            minifyEnabled false
        }
    }

    packaging {
        jniLibs {
            useLegacyPackaging true
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'io.github.webrtc-sdk:android:150.7871.01'
}
